# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TTInputPanelDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TTInputPanelDemo
  
  pod 'TTInputPanel',:path=>'../TTInputPanel'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'YYKit'

  target 'TTInputPanelDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTInputPanelDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
